var annotated_dup =
[
    [ "ACPI", "class_a_c_p_i.html", "class_a_c_p_i" ],
    [ "AHCI", "class_a_h_c_i.html", "class_a_h_c_i" ],
    [ "AHCIBlockDevice", "class_a_h_c_i_block_device.html", "class_a_h_c_i_block_device" ],
    [ "APIC", "class_a_p_i_c.html", null ],
    [ "BootBoot", "class_boot_boot.html", "class_boot_boot" ],
    [ "Color", "struct_color.html", "struct_color" ],
    [ "CPU", "class_c_p_u.html", "class_c_p_u" ],
    [ "GDT", "class_g_d_t.html", null ],
    [ "GraphicsTerminal", "class_graphics_terminal.html", "class_graphics_terminal" ],
    [ "Heap", "class_heap.html", null ],
    [ "HPET", "class_h_p_e_t.html", null ],
    [ "IBlockDevice", "class_i_block_device.html", "class_i_block_device" ],
    [ "InterruptFrame", "struct_interrupt_frame.html", "struct_interrupt_frame" ],
    [ "Interrupts", "class_interrupts.html", null ],
    [ "IOAPIC", "class_i_o_a_p_i_c.html", null ],
    [ "ITextOutput", "class_i_text_output.html", "class_i_text_output" ],
    [ "LAPIC", "class_l_a_p_i_c.html", null ],
    [ "List", "class_list.html", "class_list" ],
    [ "Logger", "class_logger.html", null ],
    [ "MemoryBackedVirtualMemoryObject", "class_memory_backed_virtual_memory_object.html", "class_memory_backed_virtual_memory_object" ],
    [ "MMIOVirtualMemoryObject", "class_m_m_i_o_virtual_memory_object.html", "class_m_m_i_o_virtual_memory_object" ],
    [ "PCIDevice", "class_p_c_i_device.html", "class_p_c_i_device" ],
    [ "PCIe", "class_p_c_ie.html", null ],
    [ "PCIeBusSegment", "struct_p_c_ie_bus_segment.html", "struct_p_c_ie_bus_segment" ],
    [ "PhysicalAllocator", "class_physical_allocator.html", null ],
    [ "PortIO", "class_port_i_o.html", null ],
    [ "ScopedCritical", "class_scoped_critical.html", "class_scoped_critical" ],
    [ "ScopedSpinlock", "class_scoped_spinlock.html", "class_scoped_spinlock" ],
    [ "SerialPort", "class_serial_port.html", "class_serial_port" ],
    [ "Spinlock", "class_spinlock.html", "class_spinlock" ],
    [ "Timer", "class_timer.html", "class_timer" ],
    [ "UncacheablePageVirtualMemoryObject", "class_uncacheable_page_virtual_memory_object.html", "class_uncacheable_page_virtual_memory_object" ],
    [ "VirtualAddressSpace", "class_virtual_address_space.html", "class_virtual_address_space" ],
    [ "VirtualMemoryObject", "class_virtual_memory_object.html", "class_virtual_memory_object" ]
];