var hierarchy =
[
    [ "ACPI", "class_a_c_p_i.html", null ],
    [ "AHCI", "class_a_h_c_i.html", null ],
    [ "APIC", "class_a_p_i_c.html", null ],
    [ "BootBoot", "class_boot_boot.html", null ],
    [ "Color", "struct_color.html", null ],
    [ "CPU", "class_c_p_u.html", null ],
    [ "CPU::CPUID", "struct_c_p_u_1_1_c_p_u_i_d.html", null ],
    [ "GDT", "class_g_d_t.html", null ],
    [ "ACPI::GenericAddressStructure", "struct_a_c_p_i_1_1_generic_address_structure.html", null ],
    [ "Heap", "class_heap.html", null ],
    [ "HPET", "class_h_p_e_t.html", null ],
    [ "IBlockDevice", "class_i_block_device.html", [
      [ "AHCIBlockDevice", "class_a_h_c_i_block_device.html", null ]
    ] ],
    [ "InterruptFrame", "struct_interrupt_frame.html", null ],
    [ "Interrupts", "class_interrupts.html", null ],
    [ "IOAPIC", "class_i_o_a_p_i_c.html", null ],
    [ "ITextOutput", "class_i_text_output.html", [
      [ "GraphicsTerminal", "class_graphics_terminal.html", null ],
      [ "SerialPort", "class_serial_port.html", null ]
    ] ],
    [ "LAPIC", "class_l_a_p_i_c.html", null ],
    [ "List< T >", "class_list.html", null ],
    [ "List< ACPI::Table * >", "class_list.html", null ],
    [ "List< AHCI * >", "class_list.html", null ],
    [ "List< Capability >", "class_list.html", null ],
    [ "List< IBlockDevice * >", "class_list.html", null ],
    [ "List< PCIDevice * >", "class_list.html", null ],
    [ "List< PCIeBusSegment * >", "class_list.html", null ],
    [ "List< PortInfo * >", "class_list.html", null ],
    [ "List< Request >", "class_list.html", null ],
    [ "List< TimedEvent * >", "class_list.html", null ],
    [ "List< u8 >", "class_list.html", null ],
    [ "List< VirtualMemoryRegion * >", "class_list.html", null ],
    [ "List< void * >", "class_list.html", null ],
    [ "Logger", "class_logger.html", null ],
    [ "BootBoot::MemoryMapEntry", "struct_boot_boot_1_1_memory_map_entry.html", null ],
    [ "PCIDevice", "class_p_c_i_device.html", null ],
    [ "PCIe", "class_p_c_ie.html", null ],
    [ "PCIeBusSegment", "struct_p_c_ie_bus_segment.html", null ],
    [ "PhysicalAllocator", "class_physical_allocator.html", null ],
    [ "CPU::Pointer", "struct_c_p_u_1_1_pointer.html", null ],
    [ "PortIO", "class_port_i_o.html", null ],
    [ "ScopedCritical", "class_scoped_critical.html", null ],
    [ "ScopedSpinlock", "class_scoped_spinlock.html", null ],
    [ "Spinlock", "class_spinlock.html", null ],
    [ "BootBoot::Structure", "struct_boot_boot_1_1_structure.html", null ],
    [ "ACPI::Table", "struct_a_c_p_i_1_1_table.html", null ],
    [ "Timer", "class_timer.html", null ],
    [ "VirtualAddressSpace", "class_virtual_address_space.html", null ],
    [ "VirtualMemoryObject", "class_virtual_memory_object.html", [
      [ "MemoryBackedVirtualMemoryObject", "class_memory_backed_virtual_memory_object.html", null ],
      [ "MMIOVirtualMemoryObject", "class_m_m_i_o_virtual_memory_object.html", null ],
      [ "UncacheablePageVirtualMemoryObject", "class_uncacheable_page_virtual_memory_object.html", null ]
    ] ]
];